# Generated by Django 5.0.1 on 2024-10-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_credit_user_alter_transaction_recipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(max_length=20)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.credit')),
            ],
        ),
    ]
