# Generated by Django 5.0.1 on 2024-10-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_creditpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpayment',
            name='payment_type',
        ),
    ]
