# Generated by Django 5.0.1 on 2024-10-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_creditpayment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='carrent_value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
