# Generated by Django 5.0.1 on 2024-10-10 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_credit_carrent_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='carrent_value',
            new_name='current_value',
        ),
    ]
